### ISSUE TITLE
module edition

### ISSUE THREAD

**Issue by CCZU-ZH** [gitmehrdad/FACE#2]
would you please give me a list of packages like requirements

**Comment by gitmehrdad** [comment]
Hi,

The first section of each notebook is devoted to importing the required packages. All notebooks are tested and verified. However, if you experience trouble running the code, consider downgrading the packages to the versions available in January 2023, when I was developing the code.

**Comment by CCZU-ZH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
