### ISSUE TITLE
model weights

### ISSUE THREAD

**Issue by zuble** [gitmehrdad/FACE#3]
Hello :)

any chance of providing the weights ? It would mean a lot.

nevertheless, 
Thanks for your work

**Comment by gitmehrdad** [comment]
Hi,

Thank you for your comment. The model weights are available at the link below:

[Model Weights](https://drive.google.com/drive/folders/1b833wE3GAEi4L9gpZphfk2ZK1dLCUPUQ?usp=sharing)
